### ISSUE TITLE
KeyError: '#BEGIN#'

### ISSUE THREAD

**Issue by forthrin** [pub12/MarkovText#2]
Is this project/maintainer active?

I'm getting the following error using the suggested example in the README. How do I resolve it?

Is it a Python 3 compatibility issue. Python 2 is being deprecated and broken on my system.

Very curious to try this software, so hoping for help.

```
$ python3 genMarkovText.py -w 20 -n 5 -d obamadict.txt
Traceback (most recent call last):
  File "genMarkovText.py", line 54, in <module>
    main(maxWordInSentence, dictFile, genNSentences)
  File "genMarkovText.py", line 43, in main
    text = markovObj.genText() 
  File "MarkovText/markov.py", line 63, in genText
    key = list(random.choice(  self.table['#BEGIN#'] ))
KeyError: '#BEGIN#'
```

**Comment by forthrin** [comment]
Stale
